platform :ios, ‘9.0’
target 'example' do
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'boost-for-react-native'
    
    pod 'React', :path => '../node_modules/react-native'
    
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'CxxBridge',
    'RCTImage',
    'RCTCameraRoll'
    ]
    
    pod 'TRCustomAlert'
    pod 'RNTroilaAlert', :path => '../../RNTroilaAlert.podspec'
end

